"""Theme-sync: recolor the deck from end-4's matugen palette.

Reads the generated material colors and emits a small CSS layer that maps the
Tailwind shades the templates use onto the palette — so the deck matches your
desktop/wallpaper without rewriting every class. Regenerated by matugen on
wallpaper change; the deck picks it up on reload.

Danger colors (red/amber buttons) are intentionally NOT remapped.
"""

from __future__ import annotations

import json
from pathlib import Path

COLORS_FILE = Path.home() / ".local/state/quickshell/user/generated/colors.json"

# deck CSS var  ->  material color key
_MAP = {
    "--m-bg": "background",
    "--m-low": "surface_container_lowest",
    "--m-surface": "surface_container",
    "--m-high": "surface_container_high",
    "--m-on": "on_surface",
    "--m-on-var": "on_surface_variant",
    "--m-primary": "primary",
    "--m-on-primary": "on_primary",
    "--m-outline": "outline_variant",
}

# used if the palette file is missing — the original zinc/emerald dark look
_FALLBACK = {
    "--m-bg": "#000000", "--m-low": "#09090b", "--m-surface": "#18181b",
    "--m-high": "#27272a", "--m-on": "#f4f4f5", "--m-on-var": "#a1a1aa",
    "--m-primary": "#10b981", "--m-on-primary": "#052e16", "--m-outline": "#3f3f46",
}


def _vars() -> dict[str, str]:
    try:
        data = json.loads(COLORS_FILE.read_text())
        return {var: data.get(key) or _FALLBACK[var] for var, key in _MAP.items()}
    except (OSError, json.JSONDecodeError):
        return dict(_FALLBACK)


def css() -> str:
    root = ":root{" + "".join(f"{k}:{v};" for k, v in _vars().items()) + "}"
    return root + """
body{background:var(--m-bg);color:var(--m-on);}
.bg-black{background:var(--m-bg)!important;}
.bg-zinc-950,.bg-zinc-950\\/60{background:var(--m-low)!important;}
.bg-zinc-900{background:var(--m-surface)!important;}
.bg-zinc-800{background:var(--m-high)!important;}
.bg-emerald-600,.bg-emerald-700,.bg-emerald-500{background:var(--m-primary)!important;color:var(--m-on-primary)!important;}
.text-emerald-500{color:var(--m-primary)!important;}
.text-zinc-100,.text-zinc-200{color:var(--m-on)!important;}
.text-zinc-300,.text-zinc-400{color:var(--m-on-var)!important;}
.border-zinc-700,.border-zinc-800{border-color:var(--m-outline)!important;}
input[type=range]{accent-color:var(--m-primary);}
"""
